hw8: 
	gcc Nonblock_open.c -o Nonblock_open
	gcc Block_open.c -o Block_open
	gcc Nonblock_Read_Write.c -o Nonblock_Read_Write
	gcc Block_Read_Write.c -o Block_Read_Write
clean:
	rm Block_Read_Write
	rm Nonblock_Read_Write
	rm Block_open
	rm Nonblock_open
